var favorite_Julia = '<table style= width:100%><br><tr><td>Julia</td><td>2</td><td>Classics</td><td>Providence</td></table>';
var favorite_Dylan = '<table style= width:100%><br><tr><td>Dylan</td><td>2</td><td>APMA-CS</td><td>Boston</td></table>';
var favorite_Arnie = 'Value not found.';
var favorite_CS = '<table style= width:100%><br><tr><td>Owen</td><td>2</td><td>CS</td><td>Cleveland</td>';
favorite_CS += '<br><tr><td>Dylan</td><td>2</td><td>APMA-CS</td><td>Boston</td></table>';
var favorite_2 = '<table style= width:100%><br><tr><td>Dylan</td><td>2</td><td>CS</td><td>Cleveland</td>';
favorite_2 += '<br><tr><td>Julia</td><td>2</td><td>Acting</td><td>London</td></table>';
var multi_Dylan = '<table style= width:100%><br><tr><td>Dylan</td><td>2</td><td>CS</td><td>Cleveland</td>';
multi_Dylan += '<br><tr><td>Dylan</td><td>4</td><td>Classics</td><td>Providence</td></table>';
export { favorite_Dylan, favorite_Arnie, favorite_CS, favorite_Julia, favorite_2, multi_Dylan };
